### ISSUE TITLE
Change icon when enabled

### ISSUE THREAD

**Issue by agent255** [TWolczanski/linux-autoscroll#1]
Is it possible to change the mouse  icon when it is enabled?

**Comment by TWolczanski** [comment]
Yes, at least on GNOME and Budgie. I've just updated README, you can try to follow the instructions and hopefully you'll make it work.

**Comment by davigamer987** [comment]
Also want this

**Comment by agent255** [comment]
@TWolczanski Please reply if it is possible?

**Comment by TWolczanski** [comment]
It's probably possible but it looks like it isn't that easy and would presumably require an additional C script. I'll let you know once I figure out how to implement it.

**Comment by TWolczanski** [comment]
I finally found time to implement this.
@agent255 @davigamer987 @Rayannhh @guigirl42 @Jire @adeliktas
please check out the latest commit and verify that it works. Also, let me know what you think about the default icon as I created it myself.

**Comment by adeliktas** [comment]
@TWolczanski good work, this issue is solved. I've noticed missing functionalities, it seems that you based it of an older commit in the PR https://github.com/TWolczanski/linux-autoscroll/pull/6. There were many pushes meanwhile until 25. Dec, which you could use to update the tool with.

**Comment by guigirl42** [comment]
>check out the latest commit and verify that it works

It works _really_ well. 👍

>let me know what you think about the default icon

I think it looks very stylish.😆

Thanks & congratulations! 🤗

**Comment by TWolczanski** [comment]
@adeliktas @guigirl42 
Thanks for feedback!

> I've noticed missing functionalities

If you're talking about clearing the clipboard on middle mouse button click, I'm actually thinking about adding a different functionality: a possibility to enter and exit the scroll mode by _scrolling_, not _clicking_ the wheel. This would prevent not only unintentional pasting but also invoking actions that are assigned to the middle mouse button, e.g. opening a link a new tab. If this doesn't work as I imagine, then I'll think about clearing the clipboard instead.

**Comment by adeliktas** [comment]
> @adeliktas @guigirl42 Thanks for feedback!
> 
> > I've noticed missing functionalities
> 
> If you're talking about clearing the clipboard on middle mouse button click, I'm actually thinking about adding a different functionality: a possibility to enter and exit the scroll mode by _scrolling_, not _clicking_ the wheel. This would prevent not only unintentional pasting but also invoking actions that are assigned to the middle mouse button, e.g. opening a link a new tab. If this doesn't work as I imagine, then I'll think about clearing the clipboard instead.

I was also refering to quickscroll (holding and releasing scroll within timespan) and using Qtimer. See latest version.

A scroll experience as in firefox/windows would be desirable. The point of autoscroll imo is to not having to use the scroll wheel, so i would suggest adding such an scrolling feature as optional.

**Comment by TWolczanski** [comment]
Never mind, the functionality I mentioned is probably not possible to implement with pynput. I'll add the possibility to clear the clipboard instead.

Anyway, I think this issue is solved, so I'll close it.
