### ISSUE TITLE
I can't run autoscroll.py

### ISSUE THREAD

**Issue by cclockworks** [TWolczanski/linux-autoscroll#11]
Hello, when i try to run autoscroll.py I get these errors. Same happens with autoscroll_no_icon.py

![screenshot KL4pAzXWxRzYnMvmM8t](https://user-images.githubusercontent.com/76880811/162631942-31bf00fc-9f4c-4e9c-b960-24b265f27c88.png)

**Comment by TWolczanski** [comment]
Hi,
did you add a valid shebang to the file?

**Comment by cclockworks** [comment]
> 

I think so, I just followed the installation guide on README.md

**Comment by TWolczanski** [comment]
You must have done something wrong. How does your shebang look like exactly? And what is the full path to your virtual environment?
