### ISSUE TITLE
pynput depreciated

### ISSUE THREAD

**Issue by Loki-101** [TWolczanski/linux-autoscroll#13]
Script can no longer be installed via instructions, as pynput or a component pynput needs is depreciated. Full error from python3 -m pip install pynput pasted below:

Collecting pynput
  Using cached pynput-1.7.6-py2.py3-none-any.whl (89 kB)
Requirement already satisfied: python-xlib>=0.17 in ./.autoscroll/lib/python3.10/site-packages (from pynput) (0.31)
Collecting evdev>=1.3
  Using cached evdev-1.5.0.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in ./.autoscroll/lib/python3.10/site-packages (from pynput) (1.16.0)
Building wheels for collected packages: evdev
  Building wheel for evdev (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/evdev
      copying evdev/util.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/uinput.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/genecodes.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/ff.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/evtest.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/events.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/eventio.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/ecodes.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/device.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/__init__.py -> build/lib.linux-x86_64-3.10/evdev
      running build_ext
      running build_ecodes
      writing ecodes.c (using /usr/include/linux/input.h /usr/include/linux/input-event-codes.h /usr/include/linux/uinput.h)
      building 'evdev._input' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/evdev
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/rotterseth/.local/share/linux-autoscroll/.autoscroll/include -I/usr/include/python3.10 -c evdev/input.c -o build/temp.linux-x86_64-3.10/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
      evdev/input.c:10:10: fatal error: Python.h: No such file or directory
         10 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for evdev
  Running setup.py clean for evdev
Failed to build evdev
Installing collected packages: evdev, pynput
  Running setup.py install for evdev ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for evdev did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running install
      /home/rotterseth/.local/share/linux-autoscroll/.autoscroll/lib64/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/evdev
      copying evdev/util.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/uinput.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/genecodes.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/ff.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/evtest.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/events.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/eventio_async.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/eventio.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/ecodes.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/device.py -> build/lib.linux-x86_64-3.10/evdev
      copying evdev/__init__.py -> build/lib.linux-x86_64-3.10/evdev
      running build_ext
      ecodes.c already exists ... skipping build_ecodes
      building 'evdev._input' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/evdev
      gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/rotterseth/.local/share/linux-autoscroll/.autoscroll/include -I/usr/include/python3.10 -c evdev/input.c -o build/temp.linux-x86_64-3.10/evdev/input.o -std=c99 -Wno-error=declaration-after-statement
      evdev/input.c:10:10: fatal error: Python.h: No such file or directory
         10 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> evdev

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by TWolczanski** [comment]
Hi,
please make sure that you have the `python3-dev` package installed. I should have written in README that it is required.

**Comment by Loki-101** [comment]
Works like a charm now. Thank you!!
