### ISSUE TITLE
Alternative button to stop the AutoScroll operation?

### ISSUE THREAD

**Issue by guigirl42** [TWolczanski/linux-autoscroll#2]
Hello & congratulations for your clever handy script.

In my opinion, a modification that would make your script even more useful for some people would be if users could configure a **different** mouse button to **stop** the AutoScroll [AS] operation, after previously initiating it with the default button [which, for my use-case, i still prefer to be your default middle/wheel button].

In other words, ideally i could do these:
- Start the AS operation with middle-click
- Stop the AS operation with left-click
- Perform a selection-paste with middle-click then immediately stop the coincidental AS via left-click
***

According to the README, the AS python script can be edited to use a different mouse button. Sadly, whilst one of my mice is 5-button, the other is only 3-button, ie, effectively no practical option there. 

Using this 3-button mouse as my example, using the same [atm, middle] button to _both_ start **and** stop the AS operation is not a problem in a browser, or really any non-text-input field of any app. 

However unfortunately, when one _is_ within a text-editor etc,  or even just a text-input field in a browser, clicking the wheel again to _stop_ the AS, does indeed stop the scrolling, but _also_ causes the clipboard's selection content to be pasted unintentionally. 

Similarly in reverse, if merely trying to selection-paste via the wheel-click [which i do lots & lots every day as an important part of my workflow], unfortunately then the AS operation _also_ invokes, with the only way to stop it being to do _another_ middleclick, which then does _another_ paste.

If my modification suggestion is viable, i think your script would become even more valuable than it already is. 

Thank you.

**Comment by TWolczanski** [comment]
Hi,
I've just implemented the modification you suggested. It's possible now to configure the start and stop buttons separately.

Let me know if this works for you, so I can close the issue.

**Comment by guigirl42** [comment]
Hello again

It's **wonderful**, thank you _so much_ indeed. I love it. Really nice work by you, & i very much appreciate your rapid helpfulness. Best wishes.

**Comment by guigirl42** [comment]
FYI:
https://github.com/TWolczanski/linux-autoscroll/issues/3#issuecomment-1188659581
