### ISSUE TITLE
Increased "dead-band" height?

### ISSUE THREAD

**Issue by guigirl42** [TWolczanski/linux-autoscroll#4]
Hi, me again [sorry].

A few more days' full-time usage of your script has revealed another enhancement that would increase the user experience quality / comfort ... but i don't know if such a feature is technically possible.

I might preface my description by acknowledging this _existing_ request, https://github.com/TWolczanski/linux-autoscroll/issues/1 ... if we could actually _see_ a visible AutoScroll icon at the place where we initiated the AS operation, so as to be able to constantly _see_ our current mouse-pointer displacement distance from that AS initiation, [eg, like Firefox's AutoScroll icon, or the Chrome extension (see below)] then my new request here might be less important. 

The problem i've identified is that at the moment, your script provides an _extremely_ narrow "dead-band" or window in which scrolling can be _temporarily_ halted by the user, _without_ formally terminating the current AS operation by clicking the assigned button. The use-case is as follows. When reading a long article in Firefox, or in chromium-based browsers using the "AutoScroll" Chrome Web Store extension https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan, i am used to initiating the AS operation [which then generates a visible distinctive AS icon], _slightly_ moving my mouse to begin scrolling, & reading all the visible article lines. Often [in FF or chromium-browsers with that extension] i can match my AS speed to my reading speed by dexterous mouse positioning [both those methods have superior low-speed control than your script, presumably due to limitations beyond your control]. Where i can't match speed, i simply move the mouse slightly so that the pointer coincides with the invoked AS icon, which then halts/pauses the scrolling until i then again move the mouse [ie, displacing the pointer position from the AS icon].

Unfortunately the minimum **smooth** AS speed i can achieve with your script, still exceeds my reading speed [below that minimum smooth speed, the scrolling occurs in a series of staccato line jumps, during which my ability to keep reading is seriously impaired]. To try to mimic my historic use-case workflow as described above, i try to find a dead-band by incrementally moving my pointer back against the AS direction; in effect i suppose it means i try to find by trial & error the place where i first invoked AS via the middleclick. Given i have no visual guidance as to that location other than observing if the scrolling speed continues, halts or reverses, this process is entirely inefficient & frequently ineffective. Of course i could simply keep formally ending the AS by left-clicking, then later re-middleclicking to AS again, then left-clicking again, etc, -- whilst that "works", it's also disruptive & clearly inferior to my old workflow.

If it were technically possible to create a dead-band [eg, maybe ~20 or 30 px above & below the initiation position], then even though users still would not "see" any AS icon, we would easily find the dead-band by simple mouse movement & noticing when the scrolling halts. Knowing this, my original workflow would then be possible even with your script, viz: invoke AS, begin scrolling & reading, temporarily pause the AS by nudging the pointer into the easily-discovered dead-band, reading, AS'ing by leaving the dead-band, pausing, reading, AS'ing, pausing etc.

Personally i still suspect that having a visible AS icon might be better, but in its absence a dead-band would still increase script usability.

Thanks.

**Comment by guigirl42** [comment]
Here's a picture showing the Firefox AS icon.

![image](https://user-images.githubusercontent.com/76090786/140669899-dde3ecb6-24cd-4f2f-9525-0073ac09b785.png)

As soon as i displace the ordinary pointer from the invoked AS icon [by mouse movement], the scrolling begins. Returning the pointer to the AS icon halts the scrolling, even though the AS operation is still active [until i eventually cancel it manually via left-click].

With your script, in lieu of the formal AS icon _per se_, a dead-band at that place would still facilitate my described operating mode.

**Comment by TWolczanski** [comment]
Hi!
The "dead-band" behavior is quite easy to implement, but I'm still trying to figure out how to create that icon effect.

**Comment by guigirl42** [comment]
>The "dead-band" behavior is quite easy to implement

Oh, that sounds nice then. Do you have an idea of _possible_ timing for it pls? As i said, if we could have a dead-band, the "need" for an actual AS icon rather diminishes, IMO.

**Comment by TWolczanski** [comment]
I've just implemented it, check out the latest commit.

What do you think the default size of the band should be? Right now it's 30 px.

**Comment by guigirl42** [comment]
Oh **thanks so much**, it works _beautifully_! With this new enhancement, IMO your script's usability is now simply marvellous. Being able to keep the AS function _active_, yet at-will _pause_ it by moving gently into the dead-band, then out again to _resume_ without needing to be constantly clicking, truly makes using this script comfortable. Before, it actually kept stressing me out, as the page constantly see-sawed up & down, up & down whilst i desperately tried to trial-&-error find the "0 px" initiation point. Now, using it is entirely relaxing.

IMO 30 px works perfectly fine. Personally, because i am a HHGTTG fan/tragic, i changed mine to be "42"... not for any actual usability benefit, just me being silly. ;-)

**Comment by guigirl42** [comment]
FYI:
https://github.com/TWolczanski/linux-autoscroll/issues/3#issuecomment-1188659581
