### ISSUE TITLE
Installation error: invalid command bdist_wheel

### ISSUE THREAD

**Issue by d9k** [TWolczanski/linux-autoscroll#7]
During
`python3 -m pip install pynput`:

```
error: invalid command 'bdist_wheel'
```

Correct command should be:
`python3 -m pip install wheel pynput`:

**Comment by TWolczanski** [comment]
I added `python3 -m pip install wheel` to README, although `python3 -m pip install pynput` works fine on my machine:

![pynput](https://user-images.githubusercontent.com/73614115/147618416-7c958757-287f-42c3-aaf9-d5d97cdbba02.png)
